<?xml version="1.0"?>
<!-- Author: Peter Jochem
     Email: peterjochem2020@u.northwestern.edu
     Date: 09/29/2020   -->
<robot name="hopping_robot" xmlns:xacro="http://ros.org/wiki/xacro">
	
	<xacro:property name="torso_width" value="0.4" />
        <xacro:property name="torso_height" value="0.4" />
        <xacro:property name="torso_depth" value="0.4" />
        <xacro:property name="torso_mass" value="1.0" />

	<xacro:property name="leg_length" value="1.0" />
	<xacro:property name="leg_radius" value="0.05"/>
	<xacro:property name="leg_mass" value="1.0" />

	<xacro:property name="foot_width" value="0.25" />
        <xacro:property name="foot_height" value="0.60" />
        <xacro:property name="foot_depth" value="0.05" />
	<xacro:property name="foot_mass" value="1.0" />
		
	<link name="torso">
		<visual>
			<geometry>
				<box size="${torso_width} ${torso_height} ${torso_depth}" />
			</geometry>
		
			<material name="gray">
				<!-- color rgba="255 0 0 0.75" / -->
			</material>
			<origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
		</visual>
	
		<inertial>
      			<origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
			<mass value = "1.0"/>
			
			<!-- Fix the inertia tag-->
			<inertia ixx="${(1.0/12.0) * torso_mass * ( (torso_height * torso_height) + (torso_depth * torso_depth) ) }" 
                                 iyy="${(1.0/12.0) * torso_mass * ( (torso_width * torso_width) + (torso_depth * torso_depth) ) }" 
                                 izz="${(1.0/12.0) * torso_mass * ( (torso_width * torso_width) + (torso_height * torso_height) ) }"/>
    		</inertial>

		<collision>
      			<origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
    	  		<geometry>
        			<box size="${torso_width} ${torso_height} ${torso_depth}" />
     			</geometry>
		</collision>        		
        </link>

	<link name="leg">
		
		 <visual>
                        <geometry>
				 <cylinder length="${leg_length}" radius="${leg_radius}"/>
                        </geometry>
                
                        <material name="gray">
                                <!-- color rgba="0 0 255 0.4" / -->
                        </material>
			<origin rpy="0 0 0" xyz="0 0 0"/>
                </visual>
        
                <inertial>
			<origin rpy="0 0 0" xyz="0 0 0"/>
                        <mass value = "1.0"/>

			<inertia ixx="${ (1.0/12.0) * leg_mass * leg_length * leg_length}" 
				 iyy="${ (1.0/12.0) * leg_mass * leg_length * leg_length}" 
				 izz="${ (1.0/12.0) * leg_mass * leg_length * leg_length}" />
                </inertial>

                <collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
                        <geometry>
                        	<cylinder length="${leg_length}" radius="${leg_radius}"/>
                        </geometry>
                </collision>
	</link>

	<link name="foot">
		<visual>
                        <geometry>
				<box size="${foot_width} ${foot_height} ${foot_depth}" />
                        </geometry>

                        <material name="gray">
                                <!-- color rgba="0 255 0 0.5" / -->
                        </material>
			<origin rpy="0 0 0" xyz="0.0 ${-foot_height/2} 0.0"/>
                </visual>

                <inertial>
			<origin rpy="0 0 0" xyz="0.0 ${-foot_height/2} 0.0"/>
                        <mass value = "1.0"/>

                        <!-- Fix the inertia tag-->
                        <inertia ixx="${(1.0/12.0) * foot_mass * ( (foot_height * foot_height) + (foot_depth * foot_depth) ) }" 
                                 iyy="${(1.0/12.0) * foot_mass * ( (foot_width * foot_width) + (foot_depth * foot_depth) ) }" 
                                 izz="${(1.0/12.0) * foot_mass * ( (foot_width * foot_width) + (foot_height * foot_height) ) }"/>
                </inertial>

                <collision>
			<origin rpy="0 0 0" xyz="0.0 ${-foot_height/2} 0.0"/>
                        <geometry>
                                <box size="${foot_width} ${foot_height} ${foot_depth}" />
                        </geometry>
                </collision>
        </link>
	
	<joint name="torso_leg" type="fixed">
		<parent link="torso"/>
                <child link="leg"/>
		<origin rpy="0 0 0" xyz="0.0 0.0 ${-leg_length/2 - torso_depth/2}"/>
		<axis xyz="0 0 0"/>

	</joint>
	
	<joint name="leg_foot" type="revolute">
		<origin xyz="0.0 0.0 ${-leg_length/2 - foot_depth/2}" rpy="0 0 0" />
	  	<axis xyz = "1 0 0" />
	  	<parent link="leg" />
		<child link="foot" />

		<!-- What to set these to? -->
	  	<limit velocity="1.0" effort="10" lower="0.0" upper="1.57"/>
  	</joint>
	
	 <transmission name="leg_foot_trans" type="transmission_interface/SimpleTransmission">
                <joint name="leg_foot_trans" />

                <actuator name="leg_foot_trans"/>

                <!-- What to set these to? -->
                <motorInertia>0.0000049</motorInertia>
                <mechanicalReduction>50</mechanicalReduction>
        </transmission>
	
</robot>

